name: CI

on:
  push:
    branches: [master]
    pull_request:
      types: [opened, reopened]
      branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install
      - name: Build Extension
        run: npm run build
      - name: Get Version
        run: echo "VERSION=$(node actionUtils.js)" >> $GITHUB_ENV
      - name: ECHO Version
        run: echo $Version
      - name: Upload Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: TrackingDetector_${{ env.VERSION}}.zip
          path: ./dist

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: TrackingDetector_${{ env.VERSION }}.zip"
          tag: ${{ env.Version }}
          token: ${{ secrets.GITHUB_TOKEN }}
